import comp from "E:/Resources/Projects/MyProjects/LysBlog/foreverBlogs/src/.vuepress/.temp/pages/blogs/0_深度学习/Transofrmer架构详解与PyTorch实现（附代码讲解）/Transofrmer架构详解与PyTorch实现（附代码讲解）.html.vue"
const data = JSON.parse("{\"path\":\"/blogs/0_%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/Transofrmer%E6%9E%B6%E6%9E%84%E8%AF%A6%E8%A7%A3%E4%B8%8EPyTorch%E5%AE%9E%E7%8E%B0%EF%BC%88%E9%99%84%E4%BB%A3%E7%A0%81%E8%AE%B2%E8%A7%A3%EF%BC%89/Transofrmer%E6%9E%B6%E6%9E%84%E8%AF%A6%E8%A7%A3%E4%B8%8EPyTorch%E5%AE%9E%E7%8E%B0%EF%BC%88%E9%99%84%E4%BB%A3%E7%A0%81%E8%AE%B2%E8%A7%A3%EF%BC%89.html\",\"title\":\"Transofrmer架构详解与PyTorch实现（附代码讲解）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Transofrmer架构详解与PyTorch实现（附代码讲解）\",\"date\":\"2025-11-09T15:20:09.000Z\",\"categories\":[\"深度学习\"],\"tags\":[\"深度学习\"],\"sticky\":1,\"description\":\"0 引言 在 Transformer 出现之前，主流的自然语言处理模型是 RNN（循环神经网络） 和 LSTM（长短期记忆网络）。 这些模型的主要问题是： 不能并行：RNN 需要一个词一个词地处理，训练速度慢。 记忆力差：当句子很长时，前面的信息容易“被遗忘”。 Transformer 出现后，直接抛弃了循环结构，用**注意力机制（Attention）...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Transofrmer架构详解与PyTorch实现（附代码讲解）\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-11-09T15:20:09.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"二进制星辰\\\",\\\"url\\\":\\\"https://blog.csdn.net/qq_63786218?type=blog\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/blogs/0_%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/Transofrmer%E6%9E%B6%E6%9E%84%E8%AF%A6%E8%A7%A3%E4%B8%8EPyTorch%E5%AE%9E%E7%8E%B0%EF%BC%88%E9%99%84%E4%BB%A3%E7%A0%81%E8%AE%B2%E8%A7%A3%EF%BC%89/Transofrmer%E6%9E%B6%E6%9E%84%E8%AF%A6%E8%A7%A3%E4%B8%8EPyTorch%E5%AE%9E%E7%8E%B0%EF%BC%88%E9%99%84%E4%BB%A3%E7%A0%81%E8%AE%B2%E8%A7%A3%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"博客演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Transofrmer架构详解与PyTorch实现（附代码讲解）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"0 引言 在 Transformer 出现之前，主流的自然语言处理模型是 RNN（循环神经网络） 和 LSTM（长短期记忆网络）。 这些模型的主要问题是： 不能并行：RNN 需要一个词一个词地处理，训练速度慢。 记忆力差：当句子很长时，前面的信息容易“被遗忘”。 Transformer 出现后，直接抛弃了循环结构，用**注意力机制（Attention）...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"深度学习\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-11-09T15:20:09.000Z\"}]]},\"readingTime\":{\"minutes\":11.43,\"words\":3430},\"filePathRelative\":\"blogs/0_深度学习/Transofrmer架构详解与PyTorch实现（附代码讲解）/Transofrmer架构详解与PyTorch实现（附代码讲解）.md\",\"excerpt\":\"<h2>0 引言</h2>\\n<p>在 Transformer 出现之前，主流的自然语言处理模型是 <strong>RNN（循环神经网络）</strong> 和 <strong>LSTM（长短期记忆网络）</strong>。<br>\\n这些模型的主要问题是：</p>\\n<ul>\\n<li><strong>不能并行</strong>：RNN 需要一个词一个词地处理，训练速度慢。</li>\\n<li><strong>记忆力差</strong>：当句子很长时，前面的信息容易“被遗忘”。</li>\\n</ul>\\n<p>Transformer 出现后，直接抛弃了循环结构，用**注意力机制（Attention）**取而代之，让模型一次就能“看完整句话”，快速理解长距离依赖。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
