import comp from "E:/Resources/Projects/MyProjects/LysBlog/foreverBlogs/src/.vuepress/.temp/pages/blogs/0_深度学习/从零理解LeNet：卷积神经网络的起点与启示/从零理解LeNet：卷积神经网络的起点与启示.html.vue"
const data = JSON.parse("{\"path\":\"/blogs/0_%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/%E4%BB%8E%E9%9B%B6%E7%90%86%E8%A7%A3LeNet%EF%BC%9A%E5%8D%B7%E7%A7%AF%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E7%9A%84%E8%B5%B7%E7%82%B9%E4%B8%8E%E5%90%AF%E7%A4%BA/%E4%BB%8E%E9%9B%B6%E7%90%86%E8%A7%A3LeNet%EF%BC%9A%E5%8D%B7%E7%A7%AF%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E7%9A%84%E8%B5%B7%E7%82%B9%E4%B8%8E%E5%90%AF%E7%A4%BA.html\",\"title\":\"从零理解LeNet：卷积神经网络的起点与启示\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"从零理解LeNet：卷积神经网络的起点与启示\",\"date\":\"2025-10-24T10:09:42.000Z\",\"categories\":[\"深度学习\"],\"tags\":[\"深度学习\"],\"sticky\":0,\"description\":\"0 摘要 在当今深度学习的浪潮中，卷积神经网络无疑是最耀眼的明星之一，它在图像识别、目标检测、自然语言处理等领域都取得了革命性的成果。然而，当我们谈论 CNN 时，有一个名字是绕不开的，那就是 LeNet-5。 LeNet-5 是由“深度学习三巨头”之一的 Yann LeCun（杨立昆）教授在 1998 年提出的，是最早的、也是最经典的卷积神经网络之一...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"从零理解LeNet：卷积神经网络的起点与启示\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-10-24T10:09:42.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"二进制星辰\\\",\\\"url\\\":\\\"https://blog.csdn.net/qq_63786218?type=blog\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/blogs/0_%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/%E4%BB%8E%E9%9B%B6%E7%90%86%E8%A7%A3LeNet%EF%BC%9A%E5%8D%B7%E7%A7%AF%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E7%9A%84%E8%B5%B7%E7%82%B9%E4%B8%8E%E5%90%AF%E7%A4%BA/%E4%BB%8E%E9%9B%B6%E7%90%86%E8%A7%A3LeNet%EF%BC%9A%E5%8D%B7%E7%A7%AF%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E7%9A%84%E8%B5%B7%E7%82%B9%E4%B8%8E%E5%90%AF%E7%A4%BA.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"博客演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"从零理解LeNet：卷积神经网络的起点与启示\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"0 摘要 在当今深度学习的浪潮中，卷积神经网络无疑是最耀眼的明星之一，它在图像识别、目标检测、自然语言处理等领域都取得了革命性的成果。然而，当我们谈论 CNN 时，有一个名字是绕不开的，那就是 LeNet-5。 LeNet-5 是由“深度学习三巨头”之一的 Yann LeCun（杨立昆）教授在 1998 年提出的，是最早的、也是最经典的卷积神经网络之一...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"深度学习\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-10-24T10:09:42.000Z\"}]]},\"readingTime\":{\"minutes\":8.33,\"words\":2499},\"filePathRelative\":\"blogs/0_深度学习/从零理解LeNet：卷积神经网络的起点与启示/从零理解LeNet：卷积神经网络的起点与启示.md\",\"excerpt\":\"<h2>0 摘要</h2>\\n<p>在当今深度学习的浪潮中，卷积神经网络无疑是最耀眼的明星之一，它在图像识别、目标检测、自然语言处理等领域都取得了革命性的成果。然而，当我们谈论 CNN 时，有一个名字是绕不开的，那就是 <strong>LeNet-5</strong>。</p>\\n<p>LeNet-5 是由“深度学习三巨头”之一的 Yann LeCun（杨立昆）教授在 1998 年提出的，是最早的、也是最经典的卷积神经网络之一。它最初被设计用于解决手写数字识别问题（著名的 MNIST 数据集），并取得了巨大成功，尤其是在银行业的支票识别系统中得到了广泛应用。</p>\\n<p>尽管 LeNet-5 的结构在今天看来相对简单，但它奠定了现代 CNN 架构的基础。理解 LeNet-5 对于深入学习 CNN 的原理至关重要。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
