import comp from "E:/Resources/Projects/MyProjects/LysBlog/foreverBlogs/src/.vuepress/.temp/pages/blogs/1_工具与框架/Pytorch离线安装（三步解决）/Pytorch离线安装（三步解决）.html.vue"
const data = JSON.parse("{\"path\":\"/blogs/1_%E5%B7%A5%E5%85%B7%E4%B8%8E%E6%A1%86%E6%9E%B6/Pytorch%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%EF%BC%88%E4%B8%89%E6%AD%A5%E8%A7%A3%E5%86%B3%EF%BC%89/Pytorch%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%EF%BC%88%E4%B8%89%E6%AD%A5%E8%A7%A3%E5%86%B3%EF%BC%89.html\",\"title\":\"Pytorch离线安装（三步解决）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Pytorch离线安装（三步解决）\",\"date\":\"2025-03-30T19:24:35.000Z\",\"categories\":[\"工具与框架\"],\"tags\":[\"pytorch\",\"环境配置\"],\"sticky\":0,\"description\":\"0 引言 pytorch作为模型训练所需要的框架，随着人工智能的发展，模型的训练被越来越多的人熟知并使用，而pytorch作为当下最流行的训练框架，自然而然被用的更多。然而此包的大小有2G多，正常的命令行安装由于是国外的服务器，一般是很难安装成功的。有时使用清华镜像也无法安装成功，而此时就能用最后一招“离线安装”几乎能保证百分百安装成功。 1 匹配版本...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Pytorch离线安装（三步解决）\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-03-30T19:24:35.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"二进制星辰\\\",\\\"url\\\":\\\"https://blog.csdn.net/qq_63786218?type=blog\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/blogs/1_%E5%B7%A5%E5%85%B7%E4%B8%8E%E6%A1%86%E6%9E%B6/Pytorch%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%EF%BC%88%E4%B8%89%E6%AD%A5%E8%A7%A3%E5%86%B3%EF%BC%89/Pytorch%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%EF%BC%88%E4%B8%89%E6%AD%A5%E8%A7%A3%E5%86%B3%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"博客演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Pytorch离线安装（三步解决）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"0 引言 pytorch作为模型训练所需要的框架，随着人工智能的发展，模型的训练被越来越多的人熟知并使用，而pytorch作为当下最流行的训练框架，自然而然被用的更多。然而此包的大小有2G多，正常的命令行安装由于是国外的服务器，一般是很难安装成功的。有时使用清华镜像也无法安装成功，而此时就能用最后一招“离线安装”几乎能保证百分百安装成功。 1 匹配版本...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"环境配置\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"pytorch\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-03-30T19:24:35.000Z\"}]]},\"readingTime\":{\"minutes\":2.66,\"words\":797},\"filePathRelative\":\"blogs/1_工具与框架/Pytorch离线安装（三步解决）/Pytorch离线安装（三步解决）.md\",\"excerpt\":\"<h2>0 引言</h2>\\n<p>pytorch作为模型训练所需要的框架，随着人工智能的发展，模型的训练被越来越多的人熟知并使用，而pytorch作为当下最流行的训练框架，自然而然被用的更多。然而此包的大小有2G多，正常的命令行安装由于是国外的服务器，一般是很难安装成功的。有时使用清华镜像也无法安装成功，而此时就能用最后一招“<strong>离线安装</strong>”几乎能保证百分百安装成功。</p>\\n<h2>1 匹配版本</h2>\\n<p>离线安装最麻烦的一点就是需要事先匹配好版本，pytorch库的下载需要匹配三个<strong>torch</strong>、<strong>torchaudio</strong>和<strong>torchvision</strong>的版本，当时，这里默认大家已经安装好<strong>cuda</strong>、<strong>cudann</strong>和<strong>python解释器</strong>，确定了这三个的版本就可以确定pytorch三个包的版本。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
